var Home = "House";
console.log("synonyms of Home is House");
console.log(Home == "House");
var five = 5;
console.log("\nfive is equal to 5");
console.log(five == 5);
var Sunday = "Holyday";
console.log("\nsunday is Holyday");
console.log(Sunday == "Holyday");
var tenLacs = "one million";
console.log("tenLacs is equal to one million");
console.log(tenLacs == "one million");
var one = 1;
console.log("one is equal to 1");
console.log(one == 1);
var forty = 40;
console.log("forty is not equal to 40");
console.log(forty != 40);
var fortyTwo = 52;
console.log("fortyTwo is not equal to 52");
console.log(fortyTwo != 52);
console.log("one is not equal to 1");
console.log(one != 1);
console.log("tenLacs is not equal to 1 million");
console.log(tenLacs != "1 million");
console.log("sunday is not holyday");
console.log(Sunday != "Holyday");
